#!/bin/bash

docker run -it --rm \
    -v $HOME/Workspace:$HOME/Workspace \
    -e 'TZ=Asia/Tehran' \
    -e 'PKG_CONFIG_PATH=$HOME/Workspace/C/config' \
    -e 'PATH_ADD=$HOME/Workspace/C/qt/scripts' \
    mingw $PWD "$@"
